<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modules</name>
   <tag></tag>
   <elementGuidId>15444fc0-eeb1-47ee-a9f3-b2d7c4ba317e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Modules')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Modules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68d6efed-4dd9-4f93-a9b7-ab52b701d32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link mx-2 </value>
      <webElementGuid>b0f53b1b-fef3-4f83-858f-9da946c25f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project/666011d01cc6e634de0ff711/module</value>
      <webElementGuid>885cd34d-445a-4d93-a6cf-90adbab3cda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modules</value>
      <webElementGuid>345423c4-5a33-42f5-b2ab-d62e3b514eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content px-3&quot;]/ul[@class=&quot;nav nav-underline menu-2 d-flex&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link mx-2&quot;]</value>
      <webElementGuid>a1f4c717-6f95-4072-b08f-fff2830ccc14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Modules')]</value>
      <webElementGuid>bc903ae5-ad12-4f15-8605-6404f2481b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Releases'])[1]/following::a[1]</value>
      <webElementGuid>12cbac45-e595-4b2e-a5ea-75e636ac8bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requirements'])[1]/following::a[2]</value>
      <webElementGuid>f5bc459a-1c4e-4aef-b748-489f85c9b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Cases'])[1]/preceding::a[1]</value>
      <webElementGuid>68b92fd2-50f1-4774-8077-253ee456fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Runs'])[1]/preceding::a[2]</value>
      <webElementGuid>a3c37e34-874e-4019-aa06-881c76811f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modules']/parent::*</value>
      <webElementGuid>c8403a6d-8adc-41a8-bc06-8f3ee4625fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/project/666011d01cc6e634de0ff711/module')]</value>
      <webElementGuid>89b54971-a7d2-446e-8f8e-a5aae4a2290a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/ul/li[4]/a</value>
      <webElementGuid>bc689724-c890-4b76-ae69-f15c8a13f198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/project/666011d01cc6e634de0ff711/module' and (text() = 'Modules' or . = 'Modules')]</value>
      <webElementGuid>95b85d63-ef8d-4f98-8911-efa7ba145005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
