<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Modules ()_mb-1</name>
   <tag></tag>
   <elementGuidId>cd46daae-f0e8-4485-b060-fd436a91171f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modules-container']/div/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Add Module&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c1558070-1e36-408e-9870-cf104b0ba4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/add.svg</value>
      <webElementGuid>19c595f6-e500-485f-a655-aa3786c4820a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>19c0f514-abf2-4101-a885-4f6320557336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modules-container&quot;)/div[@class=&quot;col-3 mb-3&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-header d-flex justify-content-between&quot;]/div[2]/a[@class=&quot;mx-2&quot;]/img[@class=&quot;mb-1&quot;]</value>
      <webElementGuid>671f321f-3f18-40eb-ae39-5ac14890bcec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modules-container']/div/div/div/div[2]/a/img</value>
      <webElementGuid>4658a226-cb4b-471b-b46c-0536ef9fb564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>ce00bcc0-ca50-4a99-a1cc-97ee0e62fc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/add.svg']</value>
      <webElementGuid>55768c5f-9ca1-48c0-addc-75126cfa4b5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
