<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dashboard</name>
   <tag></tag>
   <elementGuidId>e841fd83-e69c-4f06-8ea9-17499e0b0aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.list-group-item.list-group-item-action.rounded.border.my-2.py-3.module-link > div.form-check > label.form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module-list']/a/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#module-list >> internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>277d6d9f-96be-47f6-be9f-5b7a40d7c901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>0b574288-ffe7-4777-b9a4-7205d9b7e701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>module-item-0</value>
      <webElementGuid>5b7b1207-78e2-466e-a459-dc7d35494276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>5646ee4f-a998-4be2-b7b1-64c852efa6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module-list&quot;)/a[@class=&quot;list-group-item list-group-item-action rounded border my-2 py-3 module-link&quot;]/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>03c83faf-5a95-490c-846d-bd861cfa4791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module-list']/a/div/label</value>
      <webElementGuid>c022b363-9fd8-4581-b073-d1f75de0e36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test module'])[1]/preceding::label[1]</value>
      <webElementGuid>8fded5bf-08df-4b46-8cd2-fd0f26baba2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/preceding::label[2]</value>
      <webElementGuid>39148b7b-335f-4527-a13b-6b924ec61ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/label</value>
      <webElementGuid>20ed0e0c-92cf-4442-91bb-ae8429cb2296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>d130bd24-fa48-4030-963d-edc6103707c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
