<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Requirements</name>
   <tag></tag>
   <elementGuidId>9a434c18-b799-4ccc-bcc9-c55e09cc4a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.mx-2.active.border-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Requirements')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Requirements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01246c2f-c114-4674-846c-1468389e513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link mx-2 active border-danger</value>
      <webElementGuid>a14e902d-1a4c-4f65-968d-aaf0fc193460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/project/666011d01cc6e634de0ff711/requirement/</value>
      <webElementGuid>8cda1c54-9a3a-4b85-ba55-e47418f903e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Requirements</value>
      <webElementGuid>6d5906c3-00f3-45c2-9f04-1d602eb0a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content px-3&quot;]/ul[@class=&quot;nav nav-underline menu-2 d-flex&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link mx-2 active border-danger&quot;]</value>
      <webElementGuid>bc784b4d-f575-4592-9571-040bba6b5819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Requirements')]</value>
      <webElementGuid>3dc3bbad-95a1-43dc-8bb5-96b40469fcaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::a[1]</value>
      <webElementGuid>74bb7fcf-ebeb-46ae-9525-11dff7a99e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::a[9]</value>
      <webElementGuid>9cbedea5-2c0c-4b83-896a-7e4198139c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Releases'])[1]/preceding::a[1]</value>
      <webElementGuid>bf9a7299-b2bd-4103-b3a0-e020119031eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modules'])[1]/preceding::a[2]</value>
      <webElementGuid>7f1144cd-f537-4908-9255-52cb730d1c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Requirements']/parent::*</value>
      <webElementGuid>d2d936f7-4c1e-41a5-871b-401d6113a974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/project/666011d01cc6e634de0ff711/requirement/')]</value>
      <webElementGuid>bd03c697-cead-4f14-b92a-b7262eb0ec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/ul/li[2]/a</value>
      <webElementGuid>16518005-f317-4373-ba6e-c9027afbb330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/project/666011d01cc6e634de0ff711/requirement/' and (text() = 'Requirements' or . = 'Requirements')]</value>
      <webElementGuid>f176bc86-0042-43f3-892a-86718522a4eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
