<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total_requirementKeyword</name>
   <tag></tag>
   <elementGuidId>d910929a-4d6d-4011-afff-845bdbb24280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;requirementKeyword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='requirementKeyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search By Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>267d2e0d-445b-4818-a7bb-74061e9d5f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a55025d1-57e8-44df-b158-be17cc97b911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecea69d7-fd55-497e-82bd-995f937cceaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requirementKeyword</value>
      <webElementGuid>6722dbd5-b0d3-4e94-9184-c1988ff772e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search By Description</value>
      <webElementGuid>672a9643-c55e-4999-b2fb-88602d5d14ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>default input example</value>
      <webElementGuid>07979ebe-9c85-42fe-acdc-c2d6a113e9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;content px-3&quot;]/div[@class=&quot;container mx-auto bg-white py-3 h-100 w-100 mb-2&quot;]/div[@class=&quot;d-flex mt-3 justify-content-between w-100&quot;]/div[@class=&quot;col-9 test-cases-card ps-3 border border-0&quot;]/div[@class=&quot;card bg-body-tertiary h-100 border border-0&quot;]/div[@class=&quot;card-header&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row col-9 ms-auto my-auto align-items-center&quot;]/div[@class=&quot;col-3&quot;]/form[@class=&quot;search-requirement&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>d22ae988-ef00-489c-ab1f-503e9557652b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='requirementKeyword']</value>
      <webElementGuid>966d6ebd-e59d-4316-99a1-c63478f5ec77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/input</value>
      <webElementGuid>39c17eb7-b41d-401a-91ff-273385232313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'requirementKeyword' and @placeholder = 'Search By Description']</value>
      <webElementGuid>f0e4af06-f47d-4f2c-a457-2a9a7f848460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
