<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Release_releaseName</name>
   <tag></tag>
   <elementGuidId>d6512277-d137-46c5-84c5-d67e289e114b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#releaseName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='releaseName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Select Release&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cbde91f-783d-4cfc-893c-c5e3cb334e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>releaseName</value>
      <webElementGuid>37a859ad-f4bb-48a4-8fd5-fe896f14d22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>releaseName</value>
      <webElementGuid>f90d99ac-61e3-4c29-80f8-a9da672f2338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>releaseList</value>
      <webElementGuid>5e7d003f-11c3-4be3-a386-137e4f61e95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a Release</value>
      <webElementGuid>aec5c78d-f213-485d-a506-5e337d104cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-0 bg-light</value>
      <webElementGuid>ff256546-1070-4cef-a263-f49b0f8fdf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;releaseName&quot;)</value>
      <webElementGuid>bdfcf08a-144e-407d-bc21-e85df644cca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='releaseName']</value>
      <webElementGuid>693523f2-0d84-4ac6-8cb7-d206f3747231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addRequirement']/div/div/div[2]/div/input</value>
      <webElementGuid>f0d5c5af-528e-461b-915c-c7be226f2f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/input</value>
      <webElementGuid>1d2c665e-d1fa-4200-841a-acd2e379598b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'releaseName' and @name = 'releaseName' and @placeholder = 'Select a Release']</value>
      <webElementGuid>645daf9d-4633-4e38-a99c-847e6a0f98b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
