<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__type</name>
   <tag></tag>
   <elementGuidId>ff96ba71-824f-4875-a9a3-cbe022442a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Select Requirement Type *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4258146-d6eb-45ae-a567-750bb5f129eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>c14b5ddb-0a59-45d9-8520-7d430c2fe0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>ce2326e9-80a0-4eba-8e1f-f84d126b2779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b73b43f2-087c-46f8-ac3d-9b80d840dd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>typeList</value>
      <webElementGuid>4354286d-4292-4a90-9f67-cf027feb1684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Requirement Type</value>
      <webElementGuid>cffa1a7b-ed41-4262-8430-abb49672e53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select border-0 bg-light</value>
      <webElementGuid>bca3579d-7871-417a-a1dc-1cf81de9f608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type&quot;)</value>
      <webElementGuid>d732a2b3-c773-45fe-bd8f-707f138d10fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type']</value>
      <webElementGuid>6e7d3914-0420-4732-9c5d-347a04a2f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addRequirement']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>cb5dce0f-7154-4ac8-a161-4fb3669ec0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>94d66019-7f11-41a0-a6e8-3de4be340da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'type' and @name = 'type' and @type = 'text' and @placeholder = 'Please Enter Requirement Type']</value>
      <webElementGuid>aac413f3-2b85-41f5-8d7a-8f3913e77a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
