<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Project Alpha</name>
   <tag></tag>
   <elementGuidId>2946b2fa-4f85-4b7a-b859-222c601b0152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cards-wrapper-cf']/div[5]/a/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Project Alpha&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5ecc44d8-ab85-4d52-bf05-a2d827c3e261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Project Alpha</value>
      <webElementGuid>9340a95c-74f7-44a0-9389-8ef7b32e01e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cards-wrapper-cf&quot;)/div[@class=&quot;card grid-view&quot;]/a[1]/div[@class=&quot;card-header bg-danger text-bg-danger&quot;]/div[@class=&quot;card-project-name&quot;]/h4[1]</value>
      <webElementGuid>f786170c-753d-4006-a4ff-ee34e9eb1053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cards-wrapper-cf']/div[5]/a/div/div/h4</value>
      <webElementGuid>cf4e1a5a-02ed-4ded-9dcc-57154320b68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assgin User'])[4]/following::h4[1]</value>
      <webElementGuid>79ef2fa5-72f3-48a7-a91f-d72916133054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues'])[4]/following::h4[1]</value>
      <webElementGuid>6a866949-e2d0-47a3-a24a-b63d394f07f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created on'])[5]/preceding::h4[1]</value>
      <webElementGuid>2ac2bd87-e613-455d-8320-b0ad59ca04d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by'])[5]/preceding::h4[1]</value>
      <webElementGuid>c6d199ff-d14d-427b-a1ad-b368c1b71b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Project Alpha']/parent::*</value>
      <webElementGuid>514b1a0d-2f75-456e-a55c-442ff9bcec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/div/h4</value>
      <webElementGuid>dfa0065e-bffb-40dd-b04b-3d24e9157e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Project Alpha' or . = 'Project Alpha')]</value>
      <webElementGuid>ec9cbd88-8957-44bc-8110-ede5a3ac281c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cards-wrapper-cf']/div[6]/a/div/div/h4</value>
      <webElementGuid>1a67ac3a-6888-47a9-8521-1e1de6fc7403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assgin User'])[5]/following::h4[1]</value>
      <webElementGuid>44a81267-c495-46d8-84d9-a30d627f6ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issues'])[5]/following::h4[1]</value>
      <webElementGuid>8cf473ff-a88d-4d93-83cc-cd3d04792952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created on'])[6]/preceding::h4[1]</value>
      <webElementGuid>9ec456d2-235c-495b-bc35-f37db84ae668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by'])[6]/preceding::h4[1]</value>
      <webElementGuid>e7d3c816-729b-4ab0-a668-112d9b968ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/div/h4</value>
      <webElementGuid>dd1aa970-2257-48fc-a770-5f7dc827892f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
